### ISSUE TITLE
Syntax Error: Invalid token

### ISSUE THREAD

**Issue by PradeepKumarRajamanickam** [Highwinds/striketracker#5]
When I try to import striketracker I get the below error. I am using python3.4 on Linux Mint 17

Traceback (most recent call last):
  File "/usr/local/bin/striketracker", line 3, in <module>
    from striketracker import Command
  File "/usr/local/lib/python3.4/dist-packages/striketracker/__init__.py", line 20
    with os.fdopen(os.open(self.filename, os.O_RDONLY | os.O_CREAT, 0600), 'r') as f:
                                                                       ^
SyntaxError: invalid token

**Comment by thinkjson** [comment]
We do not currently support Python 3.x.

**Comment by alexmbird** [comment]
[This PR](https://github.com/Highwinds/striketracker/pull/6) is listed as closing the issue but it's still happening.

Steps to replicate:

```
$ pip install striketracker
$ python3.6
>>> from striketracker import APIClient as StrikeApiClient
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mock/Projects/Clients/f12/repos/highwinds-cdn-cert-uploader/venv/lib/python3.6/site-packages/striketracker/__init__.py", line 20
    with os.fdopen(os.open(self.filename, os.O_RDONLY | os.O_CREAT, 0600), 'r') as f:
                                                                       ^
SyntaxError: invalid token
^D

$ striketracker
Traceback (most recent call last):
  File "/Users/mock/Projects/Clients/f12/repos/highwinds-cdn-cert-uploader/venv/bin/striketracker", line 3, in <module>
    from striketracker import Command
  File "/Users/mock/Projects/Clients/f12/repos/highwinds-cdn-cert-uploader/venv/lib/python3.6/site-packages/striketracker/__init__.py", line 20
    with os.fdopen(os.open(self.filename, os.O_RDONLY | os.O_CREAT, 0600), 'r') as f:
                                                                       ^
SyntaxError: invalid token
```

**Comment by pradeepchittimodu** [comment]
File "<console>", line 1
    a=student(Date=02/02/1998,Full_Name="chittimodu Pradeep",email="chittimoduspradeep@gmail.com",skill="UI/UX",Platform="Django",phone_Number=9177803202,city="hyd",Duplicate=0.00)
                    ^
SyntaxError: invalid token

whlie i am writting the query in shell. i am getting error like this
